import requests

bot_token = '1146559539:AAG-XSwlhoK3lDx9eENPqpprGCZcxc5hy0s'  # Bot Token Generated by BotFather
bot_chatID = '-1001718926655'  # Telegram channel / personal ID


def telegram_bot_sendtext(bot_message):

    send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=MarkdownV2&text=' + bot_message
    response = requests.get(send_text)
    print("Sent")
    print(response.json())
    return response.json()


if __name__ == "__main__":
    telegram_bot_sendtext("BTC Going up dasdasdsa ")
